# Intro to Numpy
Este documento é uma lista de funcionalidades
específicas de numpy

Este material foi retirado do livro
```
Python for Data Analysis
by Wes McKinney
2018
```

In [1]:
import numpy as np


numpy eh muito mais rapido que python

In [4]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
my_lis = list(range(1_000_000))

In [6]:
%time for _ in range(100): my_arr2 = my_arr*2


CPU times: user 124 ms, sys: 10.2 ms, total: 134 ms
Wall time: 132 ms


In [7]:
%time for _ in range(100): my_lis2 = [2*x for x in my_lis]


CPU times: user 4.11 s, sys: 846 ms, total: 4.95 s
Wall time: 4.96 s


In [8]:
# gerando dados aleatorios 2x3
data = np.random.randn(2, 3)
data

array([[-0.26814255, -1.31714543,  0.69382992],
       [-0.05363976,  0.54445207, -0.85542207]])

In [9]:
data*10


array([[ -2.68142553, -13.17145429,   6.93829917],
       [ -0.53639759,   5.44452075,  -8.5542207 ]])

In [10]:
data + data

array([[-0.53628511, -2.63429086,  1.38765983],
       [-0.10727952,  1.08890415, -1.71084414]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

criando a partir de listas



In [13]:
data1 = [6, 7.5, 8, 0, 1]


In [15]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# numero de dimencoes
arr2.ndim

2

In [21]:
# tamanho de cada dimensao
arr2.shape

(2, 4)

In [22]:
# tipo de dados
arr2.dtype

dtype('int64')

In [28]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [40]:
# np.linspace(begin, stop, quantidade)
# quantidade de numeros do begin, a stop
# uniformemente espacados
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Data Types

In [42]:
arr1 = np.array([1,2,3])
arr1.dtype

dtype('int64')

In [43]:
arr2 = np.array([1,2,3], dtype=np.float64)
arr2.dtype

dtype('float64')

In [45]:
arr1

array([1, 2, 3])

In [46]:
arr2


array([1., 2., 3.])

In [47]:
arr1.astype(np.float64)


array([1., 2., 3.])

In [50]:
arr_str = np.array(['-1.25', '3', '4.0'])
arr_str

array(['-1.25', '3', '4.0'], dtype='<U5')

In [51]:
arr_str.astype(np.float64)


array([-1.25,  3.  ,  4.  ])

# Arithmetic

In [53]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:
arr*arr


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
arr-arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [59]:
arr2 = np.array([[0., 4., 1., ], [7., 2., 12.]])

In [60]:
arr2 > arr


array([[False,  True, False],
       [ True, False,  True]])

# Boolean Indexing

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [63]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data

array([[-0.87496003,  0.897011  ,  0.26881253,  0.94026941],
       [-0.24149991,  1.62644467, -0.04330798,  1.65725012],
       [ 1.24456339, -0.13512462, -0.13374863, -0.46844533],
       [ 0.39966907,  0.6681696 , -0.34900201, -0.52345473],
       [-1.40259222,  0.29484858, -0.93223449,  0.11095194],
       [ 0.62209502, -0.06804024, -0.36560519, -0.15977618],
       [-0.49874406, -1.14743241, -2.32154002, -0.66234573]])

In [67]:
# indices em que o valor eh Bob
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [68]:
names[names=='Bob']


array(['Bob', 'Bob'], dtype='<U4')

In [69]:
data[names=='Bob']


array([[-0.87496003,  0.897011  ,  0.26881253,  0.94026941],
       [ 0.39966907,  0.6681696 , -0.34900201, -0.52345473]])

In [70]:
data[names=='Bob', 2]


array([ 0.26881253, -0.34900201])

In [71]:
data[names=='Bob', 2:]

array([[ 0.26881253,  0.94026941],
       [-0.34900201, -0.52345473]])

In [72]:
data[names!='Bob']


array([[-0.24149991,  1.62644467, -0.04330798,  1.65725012],
       [ 1.24456339, -0.13512462, -0.13374863, -0.46844533],
       [-1.40259222,  0.29484858, -0.93223449,  0.11095194],
       [ 0.62209502, -0.06804024, -0.36560519, -0.15977618],
       [-0.49874406, -1.14743241, -2.32154002, -0.66234573]])

In [73]:
data[(names=='Bob') | (names=='Will')]

array([[-0.87496003,  0.897011  ,  0.26881253,  0.94026941],
       [ 1.24456339, -0.13512462, -0.13374863, -0.46844533],
       [ 0.39966907,  0.6681696 , -0.34900201, -0.52345473],
       [-1.40259222,  0.29484858, -0.93223449,  0.11095194]])

In [77]:
# zerando todos valores negativos
data[data<0]

array([], dtype=float64)

In [78]:
data[data<0] = 0

In [79]:
data

array([[0.        , 0.897011  , 0.26881253, 0.94026941],
       [0.        , 1.62644467, 0.        , 1.65725012],
       [1.24456339, 0.        , 0.        , 0.        ],
       [0.39966907, 0.6681696 , 0.        , 0.        ],
       [0.        , 0.29484858, 0.        , 0.11095194],
       [0.62209502, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [80]:
data[names=='Joe'] = 7


In [81]:
data


array([[0.        , 0.897011  , 0.26881253, 0.94026941],
       [7.        , 7.        , 7.        , 7.        ],
       [1.24456339, 0.        , 0.        , 0.        ],
       [0.39966907, 0.6681696 , 0.        , 0.        ],
       [0.        , 0.29484858, 0.        , 0.11095194],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])