In [1]:
import numpy as np
import os
from pathlib import Path
from matplotlib.image import imread

In [2]:
dataset_path = Path(os.path.join('..', '..', 'dataset', 'v20220930_partial'))

In [3]:
path_labels = {}

path_labels['a'] = dataset_path.joinpath('a_l/train_61')
path_labels['e'] = dataset_path.joinpath('e_l/train_65')
path_labels['i'] = dataset_path.joinpath('i_l/train_69')
path_labels['o'] = dataset_path.joinpath('o_l/train_6f')
path_labels['u'] = dataset_path.joinpath('u_l/train_75')
path_labels['A'] = dataset_path.joinpath('A_u/train_41')
path_labels['E'] = dataset_path.joinpath('E_u/train_45')
path_labels['I'] = dataset_path.joinpath('I_u/train_49')
path_labels['O'] = dataset_path.joinpath('O_u/train_4f')
path_labels['U'] = dataset_path.joinpath('U_u/train_55')

In [4]:
label_to_file = {
    k: [dataset_path / path_label / file for file in os.listdir(dataset_path / path_label)]  # NOQA:E501
    for k, path_label in path_labels.items()
}

In [5]:
X = []
y = []
for key, files in label_to_file.items():
    for path in files:
        y.append(key)
        image = imread(path)
        binary_matrix = []
        for line in image:
            binary_matrix.append([int(cell[0]) for cell in line])

        X.append(np.array(binary_matrix))

In [6]:
# transformando matriz da imagem em array de uma dimensao
X = [x.reshape(1, -1) for x in X]

In [7]:
X = np.array(X)

In [8]:
# transformando arary de labels em binarios (se eh i ou nao)
y = np.array(y)

In [9]:
y = ((y=='i')|(y=='I'))

In [10]:
y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

Usando split aleatorio stratified para separar os dados

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedShuffleSplit.html

class sklearn.model_selection.StratifiedShuffleSplit(n_splits=10, *, test_size=None, train_size=None, random_state=None)

In [11]:
from sklearn.model_selection import StratifiedShuffleSplit

In [12]:
# split entre 0, 1
# separando 20% para teste
split_test_threshold = 0.2

In [13]:
selection_iter = StratifiedShuffleSplit(n_splits=1, test_size=split_test_threshold, random_state=42)

In [14]:
train_index, test_index = next(selection_iter.split(X, y))

In [15]:
X_train = X[train_index]
X_test = X[test_index]
y_train = y[train_index]
y_test = y[test_index]

In [16]:
y_train

array([ True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False,  True,

In [17]:
y_test

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False,  True, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,

In [18]:
len(y)

900

In [19]:
len(y_train)

720

In [20]:
np.sum(y_train)

144

In [21]:
np.sum(y_train)/len(y_train)

0.2

In [22]:
len(y_test)

180

In [23]:
np.sum(y_test)

36

In [24]:
np.sum(y_test)/len(y_test)

0.2

In [25]:
type(train_index)

numpy.ndarray

In [26]:
import pickle as plk

Salvando os dados

In [27]:
with open('train_index.npy', 'wb') as f:
    np.save(f, train_index)

In [28]:
with open('test_index.npy', 'wb') as f:
    np.save(f, test_index)

In [29]:
# nao salvo pois excede espaco no git
#with open('X.npy', 'wb') as f:
#    np.save(f, X)

In [30]:
with open('y.npy', 'wb') as f:
    np.save(f, y)

In [31]:
with open('X_train.npy', 'wb') as f:
    np.save(f, X_train)

In [32]:
with open('X_test.npy', 'wb') as f:
    np.save(f, X_test)

In [33]:
with open('y_train.npy', 'wb') as f:
    np.save(f, y_train)

In [34]:
with open('y_test.npy', 'wb') as f:
    np.save(f, y_test)

Lendo os dados salvos

In [ ]:
with open('train_index.npy', 'rb') as f:
    train_index = np.load(f)

In [ ]:
with open('test_index.npy', 'rb') as f:
    test_index = np.load(f)

In [ ]:
with open('X.npy', 'rb') as f:
    X = np.load(f)

In [ ]:
with open('y.npy', 'rb') as f:
    y = np.load(f)

In [ ]:
with open('X_train.npy', 'rb') as f:
    X_train = np.load(f)

In [ ]:
with open('X_test.npy', 'rb') as f:
    X_test = np.load(f)

In [ ]:
with open('y_train.npy', 'rb') as f:
    y_train = np.load(f)

In [ ]:
with open('y_test.npy', 'rb') as f:
    y_test = np.load(f)
