# Intro to Numpy
Este documento é uma lista de funcionalidades
específicas de numpy

Este material foi retirado do livro
```
Python for Data Analysis
by Wes McKinney
2018
```

In [1]:
import numpy as np


numpy eh muito mais rapido que python

In [2]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [3]:
my_lis = list(range(1_000_000))

In [4]:
%time for _ in range(100): my_arr2 = my_arr*2


CPU times: user 164 ms, sys: 8.53 ms, total: 172 ms
Wall time: 176 ms


In [5]:
%time for _ in range(100): my_lis2 = [2*x for x in my_lis]


CPU times: user 6.11 s, sys: 451 ms, total: 6.56 s
Wall time: 7.14 s


In [6]:
# gerando dados aleatorios 2x3
data = np.random.randn(2, 3)
data

array([[-1.2524331 , -0.02831504, -0.72395129],
       [ 0.64745834, -0.25325457, -1.40213549]])

In [7]:
data*10


array([[-12.52433097,  -0.28315044,  -7.23951287],
       [  6.47458336,  -2.5325457 , -14.02135485]])

In [8]:
data + data

array([[-2.50486619, -0.05663009, -1.44790257],
       [ 1.29491667, -0.50650914, -2.80427097]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

criando a partir de listas



In [11]:
data1 = [6, 7.5, 8, 0, 1]


In [12]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# numero de dimencoes
arr2.ndim

2

In [15]:
# tamanho de cada dimensao
arr2.shape

(2, 4)

In [16]:
# tipo de dados
arr2.dtype

dtype('int64')

In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [23]:
# np.linspace(begin, stop, quantidade)
# quantidade de numeros do begin, a stop
# uniformemente espacados
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Data Types

In [24]:
arr1 = np.array([1,2,3])
arr1.dtype

dtype('int64')

In [25]:
arr2 = np.array([1,2,3], dtype=np.float64)
arr2.dtype

dtype('float64')

In [26]:
arr1

array([1, 2, 3])

In [27]:
arr2


array([1., 2., 3.])

In [28]:
arr1.astype(np.float64)


array([1., 2., 3.])

In [29]:
arr_str = np.array(['-1.25', '3', '4.0'])
arr_str

array(['-1.25', '3', '4.0'], dtype='<U5')

In [30]:
arr_str.astype(np.float64)


array([-1.25,  3.  ,  4.  ])

# Arithmetic

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr*arr


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr-arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
arr2 = np.array([[0., 4., 1., ], [7., 2., 12.]])

In [38]:
arr2 > arr


array([[False,  True, False],
       [ True, False,  True]])

In [39]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [40]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr3d[0][0]

array([1, 2, 3])

In [43]:
arr3d[0][0][0]

np.int64(1)

In [44]:
arr3d[0,0,0]

np.int64(1)

In [45]:
arr3d[0,0]

array([1, 2, 3])

In [46]:
arr3d[:, :, 2]

array([[ 3,  6],
       [ 9, 12]])

In [47]:
arr3d[1, :, 1:]

array([[ 8,  9],
       [11, 12]])

# Boolean Indexing

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
data

array([[-0.14372236,  0.58373353, -0.62859076, -1.68776363],
       [ 0.58591075,  0.16328812, -0.61610859,  2.11509781],
       [ 0.01095234, -1.25347626,  1.30901393, -0.75914179],
       [-0.12355202,  0.27445299,  1.40076038, -0.89792643],
       [-0.67614373, -0.0996626 , -0.32898694,  1.65337729],
       [-0.45141808,  1.16721188, -1.01229345, -0.61238942],
       [ 0.60165016,  0.06619344, -0.30338719, -0.5073148 ]])

In [51]:
# indices em que o valor eh Bob
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [52]:
names[names=='Bob']


array(['Bob', 'Bob'], dtype='<U4')

In [53]:
data[names=='Bob']


array([[-0.14372236,  0.58373353, -0.62859076, -1.68776363],
       [-0.12355202,  0.27445299,  1.40076038, -0.89792643]])

In [54]:
data[names=='Bob', 2]


array([-0.62859076,  1.40076038])

In [55]:
data[names=='Bob', 2:]

array([[-0.62859076, -1.68776363],
       [ 1.40076038, -0.89792643]])

In [56]:
data[names!='Bob']


array([[ 0.58591075,  0.16328812, -0.61610859,  2.11509781],
       [ 0.01095234, -1.25347626,  1.30901393, -0.75914179],
       [-0.67614373, -0.0996626 , -0.32898694,  1.65337729],
       [-0.45141808,  1.16721188, -1.01229345, -0.61238942],
       [ 0.60165016,  0.06619344, -0.30338719, -0.5073148 ]])

In [57]:
data[(names=='Bob') | (names=='Will')]

array([[-0.14372236,  0.58373353, -0.62859076, -1.68776363],
       [ 0.01095234, -1.25347626,  1.30901393, -0.75914179],
       [-0.12355202,  0.27445299,  1.40076038, -0.89792643],
       [-0.67614373, -0.0996626 , -0.32898694,  1.65337729]])

In [58]:
# zerando todos valores negativos
data[data<0]

array([-0.14372236, -0.62859076, -1.68776363, -0.61610859, -1.25347626,
       -0.75914179, -0.12355202, -0.89792643, -0.67614373, -0.0996626 ,
       -0.32898694, -0.45141808, -1.01229345, -0.61238942, -0.30338719,
       -0.5073148 ])

In [59]:
data[data<0] = 0

In [60]:
data

array([[0.        , 0.58373353, 0.        , 0.        ],
       [0.58591075, 0.16328812, 0.        , 2.11509781],
       [0.01095234, 0.        , 1.30901393, 0.        ],
       [0.        , 0.27445299, 1.40076038, 0.        ],
       [0.        , 0.        , 0.        , 1.65337729],
       [0.        , 1.16721188, 0.        , 0.        ],
       [0.60165016, 0.06619344, 0.        , 0.        ]])

In [61]:
data[names=='Joe'] = 7


In [62]:
data


array([[0.        , 0.58373353, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.01095234, 0.        , 1.30901393, 0.        ],
       [0.        , 0.27445299, 1.40076038, 0.        ],
       [0.        , 0.        , 0.        , 1.65337729],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])